### ISSUE TITLE
CI: Figure out why `expo-publish-staging` ran on PR#496

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#497]
#496 updates the `production-v1.5` branch (current production branch) with some new commits from master.

Somehow, the master/expo-publish-staging Github action spawned. This is the relevant config:
```yaml
on:
  push:
    branches:
      - master
```

I don't understand why this job spawned for this PR.
